### ISSUE TITLE
BUG : tabs appear to be duplicated & icon obscured/oversized.

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-comments#211] opened 2017-07-05 21:32 UTC
The New, Approved, Spam tabs appear on the top right as well as on the left. And, depending on which tabs are clicked, sometimes the grid field content is duplicated as well. It also appears that the icon in the CMS menu is obscured and the menu bar is oversized:

![screenshot from 2017-07-06 09-25-25](https://user-images.githubusercontent.com/8912185/27885853-a4efa1f6-622d-11e7-820a-8dc459f73572.png)

![screenshot from 2017-07-06 09-25-49](https://user-images.githubusercontent.com/8912185/27885864-ad9396d2-622d-11e7-8b2a-5dbeee4d4fbc.png)

**Comment by robbieaverill** [comment] 2017-12-12 21:29
I can't reproduce this on the latest version of SS4 and this module, however my top right corner doesn't load (AJAX failure). For me the GridFields switch correctly between comment states.

Related: https://github.com/colymba/GridFieldBulkEditingTools/issues/157

@SpiritLevel are you still able to reproduce this?

**Comment by robbieaverill** [comment] 2017-12-14 07:21
This should be fixed with #224

**Closed** 2017-12-14 21:09 UTC
Labels: affects/v4, change/patch, type/bug
