### ISSUE TITLE
No link on CMS to moderate the comments

### ISSUE THREAD

**Issue by intotheweb101** [silverstripe/silverstripe-comments#98] opened 2015-03-26 00:37 UTC
Hello 

I have a issue on my site where the comments button in the side bar isnt showing up.  I can get to it by going `/comments` and that works.  It just the fact there is no button to it.

Is there something i need to add into the code base or should this work out of the box.

Thanks
Hadlee

**Comment by tractorcow** [comment] 2015-03-26 02:19
The comments option should appear out of the box.

If you can't see it try ensuring you are logged in as an admin.

What other modules do you have installed that could affect this?

**Comment by intotheweb101** [comment] 2015-03-27 00:39
this is the required section of my composer.json

"silverstripe/cms": "3.1.*",
    	"silverstripe/framework": "3.1.*",
    	"silverstripe/advancedworkflow": "dev-master",
        "silverstripe/contentreview": "dev-master",
        "silverstripe/fulltextsearch": "dev-master",
        "silverstripe/fulltextsearch-localsolr": "dev-master",
        "custom-silverstripe-fork/googlemaps": "dev-upgrade",
        "custom-silverstripe-fork/documentconverter": "dev-upgrade",
        "silverstripe/recaptcha": "*",
        "silverstripe/spamprotection": "*",
        "silverstripe/userforms": "*",
        "custom-silverstripe-fork/onlinepayment": "dev-upgrade",
        "silverstripe/comments": "*",
        "silverstripe/secureassets": "dev-master",
        "silverstripe/timepickerfield": "dev-master",
        "unclecheese/betterbuttons": "1.2.*",
        "micschk/silverstripe-excludechildren": "dev-master",
        "micschk/silverstripe-gridfieldpages": "dev-master",
        "colymba/gridfield-bulk-editing-tools": "*"

**Comment by assertchris** [comment] 2015-04-14 05:26
@intotheweb101 This module has changed significantly in the last 2 weeks. Does this problem still occur when using `dev-master`? We'll be tagging a new release in the next month so if `dev-master` works for you then the issue is likely to resolve itself when upgrading to the next version.

**Comment by tractorcow** [comment] 2015-04-15 22:05
I'm not sure that much in the way of the modeladmin has changed.

I wonder if @intotheweb101 just changed a permission in security that hid that admin for the current user? :D (not saying that's for sure, just a possibility).

**Comment by assertchris** [comment] 2015-05-28 22:19
Still having this issue?

**Comment by tractorcow** [comment] 2015-08-20 02:27
@intotheweb101 can you please check the security setting of your group to make sure you have enabled this modeladmin for the current user?

**Comment by wilr** [comment] 2017-09-12 21:26
Closing as cannot reproduce and card +2 years old

**Closed** 2017-09-12 21:26 UTC
Labels: discussion, feedback-required/author, type/bug
